name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: "Test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: "Set up environment"
        run: |
          set -euxo pipefail
          chmod -R 700 .

      - name: "Test system software installation"
        run: sudo setup/sys_install.sh

      - name: "Test python libraries installation"
        run: sudo setup/pip_install.sh

      - name: "Test configuration set up"
        run: sudo setup/configuration.sh

      - name: "Test autostart applications set up"
        run: sudo setup/autostart_apps.sh

      - name: "Test default applications set up"
        run: sudo setup/default_apps.sh

      - name: "Test extra applications set up"
        run: sudo setup/extra_apps.sh

  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: make setup

      - run: make lint
