name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: "Test"
    timeout-minutes: 90
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: "Set up environment"
        run: |
          set -eo pipefail
          chmod -R 700 .

      - name: "Test system software installation"
        run: if ! $(sudo install/system_software.sh); then exit 1; fi

      - name: "Test python applications and libraries installation"
        run: if ! $(sudo install/python_software.sh); then exit 1; fi

      - name: "Test configuration set up"
        run: if ! $(sudo install/configuration.sh); then exit 1; fi

      - name: "Test autostart applications set up"
        run: if ! $(sudo install/autostart_apps.sh); then exit 1; fi

      - name: "Test default applications set up"
        run: if ! $(sudo install/default_apps.sh); then exit 1; fi

  lint:
    name: "Lint"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: make setup

      - run: make lint
